app = "miku-telegram-bot"
primary_region = "sea"  # Change this to your preferred region

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[processes]
  app = "python fly_standalone.py"

[healthcheck]
  path = "/status"
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"